name: Portal121Compat
version: 1.1.0
main: com.portal121compat.Portal121Compat
api-version: '1.20'
description: 爱你哟(๑╹ヮ╹๑)ﾉ-Fan404ovo Gift to ttooogggghh
website: https://github.com/Fanovo114514/Portal121Compat

commands:
  portal121compat:
    description: Portal121Compat main command
    usage: /<command> <witchredstone|reload>
    aliases:
      - p121

permissions:
  portal121compat.admin:
    description: Portal121Compat admin permission
    default: op
