name: Portal121Compat
version: '${project.version}'
main: com.portal121compat.Portal121Compat
api-version: '1.20'
description: 爱你哟(๑╹ヮ╹๑)ﾉ-Fan404ovo Gift to ttooogggghh
website: https://github.com/Fanovo114514/Portal121Compat

commands:
  portal121compat:
    description: Portal121Compat 主指令
    usage: /<command> <witchredstone|reload>
    aliases:
      - p121

permissions:
  portal121compat.admin:
    description: 允许使用 Portal121Compat 管理指令
    default: op
